#ifndef STLINK_VERSION_H_
#define STLINK_VERSION_H_

#define STLINK_VERSION       "1.6.1"
#define STLINK_VERSION_MAJOR 1
#define STLINK_VERSION_MINOR 6
#define STLINK_VERSION_PATCH 1

#endif // STLINK_VERSION_H_
